### ISSUE TITLE
Missing OpenAI and Cognitive Services DNS zones

### ISSUE THREAD

**Issue by marrobi** [microsoft/terraform-azurerm-environment-configuration#13]
Azure AI services (Microsoft.CognitiveServices/accounts) | account | privatelink.cognitiveservices.azure.us |

**Comment by marrobi** [comment]
@balteravishay @LizaShak any idea where I can find the Gov Endpoint for OpenAI? Maybe just one to add for public cloud?

**Comment by LizaShak** [comment]
Hi @marrobi , it is not documented anywhere, and I don't have access to the GOV cloud anymore. From past experience with the used suffixes in gov cloud, my guess would be that if there is one it would be - privatelink.openai.azure.us

**Comment by harryy94** [comment]
Hi. I have picked up the OpenAI work that required these two endpoints to be added to this repo. I'm not overly familiar with Azure US however did find this link that seems to verify what @LizaShak thought. I've raised the PR to add these two urls in. Thanks!
